### ISSUE TITLE
Fix missing dependency zendframework/zend-stdlib

### ISSUE THREAD

**Issue by JurJean** [Rxnet/eventstore-client#11]
The code depends on zendframework/zend-stdlib, which is a dependency of a dev dependency. Please either remove the dependency or add zendframework/zend-stdlib to require of composer.json

**Comment by Vinceveve** [comment]
Done, thank you for the advice :)

**Comment by jvdlaar** [comment]
The library is now added to the dev dependencies, but it actually is a dependency. The Writer class uses `use Zend\Stdlib\SplQueue;`

**Comment by Vinceveve** [comment]
I've just removed all dependencies on Zend Stdlib.
