### ISSUE TITLE
OnbackpressureBuffer wrong filename

### ISSUE THREAD

**Issue by SunMar** [Rxnet/eventstore-client#32]
Hi,

The file `OnbackpressureBuffer.php` is named wrong and is not following PSR-4 due to a capitalization mismatch, this is causing issues on a case-sensitive filesystem where the class cannot be found. The filename should be `OnBackPressureBuffer.php`. I'll create a PR for this later today.

**Comment by Th3Mouk** [comment]
Thank you good catch !
